name: GregDare
favicon: null
layout_spectrum: 0.2690232009626925
typography_spectrum: 0.7727466998621821
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.27254574932157993
  lightness: 0.28829230344854295
  saturation: 0.8950472148135304
  rhythmicContrast: 0.051087099593132734
purpose: []
